{
  "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextDataList",
  "FileHeader" : {
    "MagicBytesLength" : 4,
    "MagicString" : "QTD\u0000",
    "VersionBytesLength" : 4,
    "VersionNumber" : 2
  },
  "FileSize" : 52,
  "QuestTextDataList" : [ {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : "The Experiment Strikes Back",
    "MsgGmdIdx" : 0,
    "Type" : 0,
    "TypeName" : "QUEST_TEXT_TYPE_NAME"
  }, {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : "Defeat the enemy encountered",
    "MsgGmdIdx" : 1,
    "Type" : 1,
    "TypeName" : "QUEST_TEXT_TYPE_ORDER"
  }, {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : "<NAME AREA>からの報告によると\r\n魔物の勢力が一時的に増し、危険な状況にあるという",
    "MsgGmdIdx" : 2,
    "Type" : 3,
    "TypeName" : "QUEST_TEXT_TYPE_FIND_INFO"
  }, {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : "これまで数多の戦場を駆け抜け\r\n多くの魔物と対峙してきたが\r\n初めてだったよ、あんな奴は\r\nとにかく奴の繰り出す素早い攻撃には\r\n用心しすぎることはない",
    "MsgGmdIdx" : 3,
    "Type" : 4,
    "TypeName" : "QUEST_TEXT_TYPE_FIND_INFO_DETAIL"
  }, {
    "@class" : "org.sehkah.ddon.tools.extractor.common.logic.resource.entity.quest.QuestTextData",
    "Message" : "Defeat the enemy encountered",
    "MsgGmdIdx" : 4,
    "Type" : 2,
    "TypeName" : "QUEST_TEXT_TYPE_PURPOSE"
  } ]
}